// Atualize esta lista com os repositórios que você deseja destacar.
// Cada entrada aceita metadados opcionais para personalizar a exibição.
export const featuredProjects = [
  {
    owner: "tiagosousa10",
    repo: "spotify-clone",
    title: "Spotify Clone",
    category: "fullstack",
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "Zustand",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "MongoDB",
      "Socket.IO",
      "Clerk",
      "Cloudinary",
    ],
    image: "/assets/work/spotify.png",
    live: "#",
    description:
      "This Spotify clone is a comprehensive music streaming platform that replicates core features of the popular music service. The application consists of a React-based frontend and a Node.js/Express backend, providing users with a seamless music listening experience.",
  },
  {
    owner: "tiagosousa10",
    repo: "twitter-clone",
    title: "Twitter Clone",
    category: "fullstack",
    stack: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Cloudinary",
      "Tailwind CSS",
      "DaisyUI",
      "React Query",
    ],
    image: "/assets/work/twitter-clone.png",
    live: "#",
    description:
      "A full-stack social media application inspired by Twitter, built with React and Node.js. This project demonstrates modern web development practices including authentication, real-time interactions, and cloud-based image storage.",
  },
  {
    owner: "tiagosousa10",
    repo: "e-commerce-app",
    title: "E-Commerce Application",
    category: "fullstack",
    stack: ["React", "Strapi", "Node.js", "Stripe"],
    image: "/assets/work/e-commerce-app.png",
    live: "#",
    description:
      "A modern, full-stack e-commerce application built with React and Strapi, featuring product browsing, shopping cart management, and Stripe payment integration.",
  },

  {
    owner: "tiagosousa10",
    repo: "finance-dashboard-app",
    title: "Finanseer - Finance Dashboard Application",
    category: "fullstack",
    stack: [
      "TypeScript",
      "React",
      "Vite",
      "Node.js",
      "Express",
      "MongoDB",
      "MUI",
      "Recharts",
    ],
    image: "/assets/work/finance-dashboard.png",
    live: "#",
    description:
      "A comprehensive financial dashboard application built with React, TypeScript, and Node.js that provides real-time insights into revenue, expenses, products, and transactions. The application features interactive charts, data tables, and predictive analytics using linear regression models.",
  },
  {
    owner: "tiagosousa10",
    repo: "gym-typescript",
    title: "Gym Website - TypeScript React Application",
    category: "frontend",
    stack: ["TypeScript", "React", "Vite", "Tailwind CSS", "Framer Motion"],
    image: "/assets/work/gym-typescript.png",
    live: "#",
    description:
      "A modern, responsive gym website built with React, TypeScript, and Tailwind CSS. This application features smooth animations, form handling, and a beautiful user interface designed to showcase a fitness center's services and facilities.",
  },
  {
    owner: "tiagosousa10",
    repo: "e-commerce-store",
    title: "E-Commerce Store",
    category: "fullstack",
    stack: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Zustand",
      "Stripe",
      "Tailwind CSS",
      "Framer Motion",
    ],
    image: "/assets/work/e-commerce-store.png",
    live: "#",
    description:
      "A full-stack e-commerce application built with React and Node.js, featuring user authentication, product management, shopping cart, payment processing with Stripe, analytics dashboard, and coupon system.",
  },
  {
    owner: "tiagosousa10",
    repo: "chat-app-yt",
    title: "ChatApp - Real-Time Chat Application",
    category: "fullstack",
    stack: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Socket.io",
      "Tailwind CSS",
      "DaisyUI",
    ],
    image: "/assets/work/chat-app.png",
    live: "#",
    description:
      "A modern, full-stack real-time chat application built with React and Node.js. This application enables users to register, login, search for other users, and exchange real-time messages in a beautiful, responsive interface.",
  },

  {
    owner: "tiagosousa10",
    repo: "ReactJScomTypeScript-do-zero-ao-avancado/tree/master/webcarros",
    title: "WebCarros - Vehicle Marketplace",
    category: "fullstack",
    stack: [
      "TypeScript",
      "React",
      "Vite",
      "Firebase",
      "Firestore",
      "Tailwind CSS",
      "Shadcn UI",
      "React Hook Form",
      "Zod",
    ],
    image: "/assets/work/webcarros.png",
    live: "#",
    description:
      "A modern web platform for buying and selling vehicles, developed with React, TypeScript, and Firebase. The project offers a complete car listing management experience, with user authentication, image uploads, advanced search, and a responsive interface.",
  },
  {
    owner: "tiagosousa10",
    repo: "reactjs-18-com-typescript/tree/master/personal-finances",
    title: "Personal Finances",
    category: "frontend",
    stack: [
      "React",
      "TypeScript",
      "Vite",
      "Redux Toolkit",
      "Styled Components",
    ],
    image: "/assets/work/personal-finances.png",
    live: "#",
    description:
      "A modern and intuitive personal finance management application that helps you track your income, expenses, and financial balance with ease. Built with React 18, TypeScript, and a beautiful, clean interface.",
  },
];
